spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  mvc:
#    static-path-pattern: /static/**
#    templates-path-pattern : /templates/**
#mybatis:
#  type:
#  aliases:
#  package: io.guangsoft.pojo

logging:
  level:
    root: info
    com.lhy: debug
  file: log/blog-dev.log

server:
  port: 80


